name: sample-workflow
on:
  push:
    branches: [develop]


jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: checks-out your repository under $GITHUBWARKSPACE
      uses: actions/checkout@v2
    - name: use echo command 
      run: echo "sample-workflow"
